#!/bin/sh

# Set repeat delay and repeat rate
xset r rate 350 35

# Map caps lock to escape
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

xmodmap -e 'keycode 135 = Super_R'

# Map the menu button to right super
xmodmap -e 'keycode 135 = Super_R'
